'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Brand} from '@/components/brand';
import {Button} from '@/components/ui/button';
import {api,configured,supabase} from '@/lib/supabase';
import {plans,clp} from '@/lib/plans';
type Client={id:string;nombre:string;plan_comercial:string;estado_comercial:string;precio_mensual:number;limite_embarques:number;limite_documentos:number;limite_usuarios:number;contrato_inicio:string|null;contrato_fin:string|null;consumo:{embarques:number;documentos:number;usuarios:number};ejecutivos:number;gerentes:number;importadores:number;en_seguimiento:number;miembros:{id:string;nombre:string;rol:string}[]};
const examples:Client[]=[{id:'demo-1',nombre:'Agencia Horizonte · Ejemplo',plan_comercial:'crece',estado_comercial:'activo',precio_mensual:129900,limite_embarques:100,limite_documentos:500,limite_usuarios:5,contrato_inicio:'2026-09-01',contrato_fin:'2027-09-01',consumo:{embarques:34,documentos:156,usuarios:4},ejecutivos:2,gerentes:1,importadores:1,en_seguimiento:21,miembros:[{id:'a',nombre:'Administración de ejemplo',rol:'owner'},{id:'b',nombre:'Gerente de ejemplo',rol:'gerente'},{id:'c',nombre:'Ejecutivo uno',rol:'ejecutivo'},{id:'d',nombre:'Ejecutivo dos',rol:'ejecutivo'},{id:'e',nombre:'Importador de ejemplo',rol:'importador'}]},{id:'demo-2',nombre:'Comex del Pacífico · Ejemplo',plan_comercial:'emprende',estado_comercial:'piloto',precio_mensual:49900,limite_embarques:25,limite_documentos:100,limite_usuarios:2,contrato_inicio:null,contrato_fin:null,consumo:{embarques:9,documentos:42,usuarios:2},ejecutivos:1,gerentes:1,importadores:0,en_seguimiento:6,miembros:[{id:'h',nombre:'Gerente de ejemplo',rol:'gerente'},{id:'i',nombre:'Ejecutivo de ejemplo',rol:'ejecutivo'}]}];
function Usage({title,used,limit}:{title:string;used:number;limit:number}){return <div className="usage-meter"><span>{title}: <strong>{used} / {limit}</strong>{used>=limit?' · Cupo alcanzado':''}</span><progress max={limit} value={Math.min(used,limit)} aria-label={title}/></div>}
export default function Owner(){
 const [demo,setDemo]=useState(false),[ready,setReady]=useState(false),[clients,setClients]=useState<Client[]>([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[q,setQ]=useState(''),[filter,setFilter]=useState('todos'),[selected,setSelected]=useState<Client|null>(null),[busy,setBusy]=useState(false),[month,setMonth]=useState('');
 async function refresh(){const r=await api('owner');setClients(r.clientes);setMonth(r.mes);return r.clientes as Client[]}
 useEffect(()=>{const isDemo=new URLSearchParams(window.location.search).get('demo')==='1';setDemo(isDemo);if(isDemo){setClients(examples);setMonth('2026-09 · ejemplo');setReady(true);return}if(!configured()){setError('Falta conectar Supabase y habilitar tu cuenta Owner para ver clientes reales.');setReady(true);return}refresh().catch(e=>setError((e as Error).message)).finally(()=>setReady(true))},[]);
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;setBusy(true);setError('');setMessage('');const f=new FormData(event.currentTarget),planId=String(f.get('plan_id')),p=plans.find(p=>p.id===planId)!,custom=planId==='corporativo';const data={company_id:selected.id,plan_id:planId,status:String(f.get('status')),start_date:String(f.get('start_date')||'')||null,custom_price:custom?Number(f.get('price')):null,custom_shipments:custom?Number(f.get('shipments')):null,custom_documents:custom?Number(f.get('documents')):null,custom_seats:custom?Number(f.get('seats')):null};
 try{if(demo){const seats=custom?data.custom_seats!:p.seats!;if(seats<selected.consumo.usuarios)throw Error('El equipo actual supera el cupo del plan.');if(data.status==='activo'&&!data.start_date)throw Error('Define la fecha de inicio del contrato.');const end=data.start_date?new Date(data.start_date+'T12:00:00Z'):null;if(end){const m=end.getUTCMonth();end.setUTCFullYear(end.getUTCFullYear()+1);if(end.getUTCMonth()!==m)end.setUTCDate(0)}const updated={...selected,plan_comercial:planId,estado_comercial:data.status,contrato_inicio:data.start_date,contrato_fin:end?.toISOString().slice(0,10)??null,precio_mensual:custom?data.custom_price!:p.price!,limite_embarques:custom?data.custom_shipments!:p.shipments!,limite_documentos:custom?data.custom_documents!:p.documents!,limite_usuarios:seats};setClients(prev=>prev.map(c=>c.id===selected.id?updated:c));setSelected(updated);setMessage('Simulación actualizada. No se guardan cambios ni se realizan cobros.')}else{await api('owner',data);const updated=await refresh();setSelected(updated.find(c=>c.id===selected.id)??null);setMessage('Contrato actualizado y registrado en auditoría. No se ha realizado ningún cobro.')}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const visible=clients.filter(c=>c.nombre.toLowerCase().includes(q.toLowerCase())&&(filter==='todos'||c.estado_comercial===filter)),active=clients.filter(c=>c.estado_comercial==='activo'),monthly=active.reduce((n,c)=>n+c.precio_mensual,0);
 return <main className="owner-shell"><header className="owner-header"><Brand/><div className="owner-status"><span className="badge blue">Owner NavegaIA</span><Button asChild variant="outline"><Link href={demo?'/app?demo=1':'/app'}>Ver plataforma</Link></Button><Button variant="outline" onClick={async()=>{if(configured()&&!demo)await supabase().auth.signOut();window.location.assign('/login?next=owner')}}>Salir</Button></div></header><div className="owner-heading"><span className="eyebrow">ADMINISTRACIÓN DE NAVEGAIA</span><h1>Tu negocio, a la vista.</h1><p>Clientes, equipos, contratos y capacidad mensual en un solo lugar.</p></div>
 {demo&&<div className="notice">DEMOSTRACIÓN · Empresas, personas y cifras ficticias. Puedes probar los controles; los cambios desaparecen al recargar.</div>}{error&&<div className="notice error" role="alert">{error}</div>}{message&&<div className="notice" role="status">{message}</div>}
 {!ready?<p>Cargando acceso…</p>:clients.length===0&&error?<section className="card"><h2>Acceso a tu panel</h2><p className="description">Ingresa con tu cuenta y segundo factor. Solo las cuentas habilitadas como Owner NavegaIA pueden consultar este panel.</p><div className="actions"><Button asChild><Link href="/login?next=owner">Ingresar como Owner</Link></Button><Button asChild variant="outline"><Link href="/owner?demo=1">Ver demostración del panel</Link></Button></div></section>:<>
 <div className="owner-kpis">{[['Clientes registrados',clients.length],['Contratos activos',active.length],['Ejecutivos',clients.reduce((n,c)=>n+c.ejecutivos,0)],['Mensual contratado + IVA',clp(monthly)]].map(([label,value])=><section className="card" key={label}><small>{label}</small><strong>{value}</strong></section>)}</div><p className="pricing-footnote">El mensual contratado suma contratos marcados activos; no representa pagos recibidos. Consumo: {month}, hora de Chile.</p>
 <div className="owner-tools"><input aria-label="Buscar cliente" placeholder="Buscar empresa cliente…" value={q} onChange={e=>setQ(e.target.value)}/><select aria-label="Filtrar estado comercial" value={filter} onChange={e=>setFilter(e.target.value)}><option value="todos">Todos los estados</option><option value="piloto">Piloto</option><option value="activo">Activo</option><option value="suspendido">Suspendido</option></select><Button variant="outline" disabled={busy} onClick={async()=>{if(demo){setMessage('Estás viendo datos de ejemplo.');return}setBusy(true);try{await refresh();setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Actualizar</Button></div>
 <section className="card owner-table"><table><thead><tr><th>Empresa / plan</th><th>Estado</th><th>Equipo interno</th><th>Embarques / mes</th><th>Documentos / mes</th><th>Mensual + IVA</th><th>Detalle</th></tr></thead><tbody>{visible.map(c=><tr key={c.id}><td><strong>{c.nombre}</strong><small>{plans.find(p=>p.id===c.plan_comercial)?.name}</small></td><td><span className={'badge '+(c.estado_comercial==='activo'?'green':c.estado_comercial==='piloto'?'blue':'yellow')}>{c.estado_comercial}</span></td><td>{c.consumo.usuarios} / {c.limite_usuarios}<small>{c.ejecutivos} ejecutivos · {c.gerentes} gerentes</small></td><td>{c.consumo.embarques} / {c.limite_embarques}</td><td>{c.consumo.documentos} / {c.limite_documentos}</td><td>{clp(c.precio_mensual)}</td><td><Button size="sm" variant="outline" onClick={()=>{setSelected(c);setMessage('')}}>Ver cliente</Button></td></tr>)}</tbody></table>{!visible.length&&<p className="empty">No hay clientes que coincidan con esta búsqueda.</p>}</section>
 {selected&&<section className="card owner-detail" aria-label="Detalle del cliente"><div className="flex-between"><h2>{selected.nombre}</h2><Button variant="outline" onClick={()=>setSelected(null)}>Cerrar detalle</Button></div><div className="settings-grid"><div><h3>Capacidad del mes</h3><Usage title="Embarques nuevos" used={selected.consumo.embarques} limit={selected.limite_embarques}/><Usage title="Documentos" used={selected.consumo.documentos} limit={selected.limite_documentos}/><Usage title="Usuarios internos" used={selected.consumo.usuarios} limit={selected.limite_usuarios}/><p>{selected.en_seguimiento} embarques en seguimiento · {selected.importadores} accesos de importadores</p><h3>Personas de la empresa</h3><ul>{selected.miembros.map(m=><li key={m.id}>{m.nombre} · {m.rol==='owner'?'Administrador de empresa':m.rol}</li>)}</ul></div>
 <form key={selected.id+'-'+selected.plan_comercial+'-'+selected.estado_comercial} onSubmit={save}><h3>Plan y contrato</h3><div className="form-grid"><label>Plan<select name="plan_id" defaultValue={selected.plan_comercial}>{plans.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Estado<select name="status" defaultValue={selected.estado_comercial}><option value="piloto">Piloto</option><option value="activo">Activo</option><option value="suspendido">Suspendido</option></select></label><label className="full">Inicio de contrato anual<input type="date" name="start_date" defaultValue={selected.contrato_inicio??''}/></label></div><p className="description">Pago mensual, contrato de 12 meses. Fin registrado: {selected.contrato_fin??'Sin contrato activo'}. Cambiar el inicio recalcula el fin. Suspender bloquea nuevas altas y conserva consultas.</p><details><summary>Capacidad personalizada · solo Corporativo</summary><div className="form-grid">{[['price','Precio mensual CLP',selected.precio_mensual],['shipments','Embarques por mes',selected.limite_embarques],['documents','Documentos por mes',selected.limite_documentos],['seats','Usuarios internos',selected.limite_usuarios]].map(([name,label,value])=><label key={String(name)}>{label}<input type="number" name={String(name)} min={name==='price'?0:1} max={name==='price'?100000000:name==='documents'?10000000:name==='shipments'?1000000:100000} required defaultValue={value}/></label>)}</div></details><Button disabled={busy} style={{marginTop:20}}>{busy?'Guardando…':demo?'Probar cambio de plan':'Guardar contrato'}</Button></form></div></section>}
 </>}
 </main>
}
