import Link from 'next/link';
import {Check,ArrowUpRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {plans,clp} from '@/lib/plans';
export function Commercial(){return <>
<section className="section" id="planes"><div className="section-heading"><div><span className="eyebrow">CRECE A TU RITMO</span><h2>Un plan para cada operación.</h2></div><p>Una suscripción por empresa.<br/>Contrato anual · pago mensual.</p></div>
<div className="pricing-grid">{plans.map(p=><article className={'price-card '+(p.id==='crece'?'featured':'')} key={p.id}>{p.id==='crece'&&<span className="price-ribbon">PARA EQUIPOS EN CRECIMIENTO</span>}<h3>{p.name}</h3><p>{p.copy}</p><div className="price-amount">{p.price===null?'Conversemos':clp(p.price)}{p.price!==null&&<small>/mes + IVA</small>}</div><strong className="contract-note">Contrato anual · pago mensual</strong>{p.price!==null&&<small className="annual-total">Total anual: {clp(p.price*12)} + IVA</small>}<ul>{[p.shipments===null?'Embarques según contrato':p.shipments+' embarques nuevos / mes',p.documents===null?'Documentos según contrato':p.documents+' documentos / mes',p.seats===null?'Usuarios según contrato':p.seats+' usuarios internos incluidos','Seguimiento de embarques registrados','Portal del importador','Gerente y ejecutivos con permisos','Trazabilidad de cambios'].map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul><Button asChild variant={p.id==='crece'?'default':'outline'}><a href={'mailto:contacto@stardesign.cl?subject='+encodeURIComponent('NavegaIA · Solicitud plan '+p.name)}>Solicitar {p.name}<ArrowUpRight size={16}/></a></Button></article>)}</div>
<p className="pricing-footnote">Valores de lanzamiento en pesos chilenos. Los cupos se comparten por empresa y se renuevan cada mes calendario, hora de Chile; no se acumulan. Consultar un embarque existente no consume otro cupo. Los importadores no ocupan usuarios internos. Cada archivo registrado cuenta como documento (PDF, JPG o PNG, hasta 4 MB); eliminarlo no devuelve el cupo.</p><div className="notice">Contratación asistida: confirmamos la activación y las condiciones antes de iniciar el cobro. La extracción con IA y los correos automáticos requieren activación y cotización adicional; no están incluidos como servicios operativos en estos valores de lanzamiento.</div></section>
<section className="section faq-section" id="faq"><span className="eyebrow">PREGUNTAS FRECUENTES</span><h2>Antes de zarpar, resolvamos tus dudas.</h2><div className="faq-list">{[
['¿Qué cuenta como un embarque?','Un expediente que creas en NavegaIA para seguir una operación marítima, con su referencia, BL, importador y fechas. Sus cambios de estado y consultas posteriores no cuentan como nuevos embarques.'],
['¿Cómo se cuentan los documentos?','Cada archivo registrado cuenta como un documento. Una factura, un packing list y un BL cargados por separado consumen tres cupos. Corregir los datos del mismo archivo no consume otro; registrar una nueva versión sí. Las cargas canceladas después de registrar el archivo tampoco devuelven cupo.'],
['¿Qué pasa cuando se acaban los cupos?','Puedes seguir consultando tus embarques y documentos existentes. Para nuevas cargas debes esperar el siguiente mes o solicitar ampliar el plan. No hay cobros automáticos por excedentes.'],
['¿El precio es mensual o anual?','El contrato dura 12 meses y se paga en cuotas mensuales al valor indicado más IVA. La fecha de inicio, facturación y demás condiciones se confirman en la contratación asistida.'],
['¿Qué puede hacer cada rol?','El administrador de la empresa gestiona sus accesos; el gerente supervisa al equipo y la operación; el ejecutivo gestiona embarques y documentos; el importador consulta solo sus embarques y archivos compartidos. La dueña de NavegaIA tiene un panel comercial separado para clientes, planes y consumo.'],
['¿NavegaIA reemplaza Editrade o AduanaNet?','No. NavegaIA organiza el trabajo documental y el seguimiento. Continúa usando tus sistemas de transmisión. No enviamos DUS ni DIN a sistemas oficiales desde esta versión.'],
['¿La inteligencia artificial está disponible?','La pantalla de revisión permite validar y corregir documentos. La extracción automática está pendiente de activar con proveedores y definir su capacidad comercial; siempre requiere revisión humana.'],
['¿Puedo usarla desde el celular?','Sí. La interfaz se adapta a celular, tablet y computador. Las tablas amplias permiten desplazamiento horizontal para conservar la información.'],
['¿Puedo probarla antes de contratar?','Sí. La demostración usa información ficticia y no guarda documentos reales. Escríbenos para coordinar la activación de una empresa piloto.']
].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
<section className="section contact-section" id="contacto"><div><span className="eyebrow">HABLEMOS DE TU OPERACIÓN</span><h2>Encuentra tu próximo rumbo.</h2><p>Cuéntanos cuántos embarques, documentos y personas necesitas gestionar al mes.</p></div><div className="actions"><Button asChild><a href="mailto:contacto@stardesign.cl?subject=Quiero%20conocer%20NavegaIA">Solicitar demostración<ArrowUpRight size={16}/></a></Button><Button asChild variant="outline"><Link href="/app?demo=1">Explorar demo</Link></Button></div></section></>}
