import {extractionPrompt,parseExtraction} from './domain';
import {HttpError} from './server';
export async function extractDocument(bytes:Buffer){const endpoint=process.env.AZURE_DOCUMENT_ENDPOINT,key=process.env.AZURE_DOCUMENT_KEY,llm=process.env.LLM_API_KEY,model=process.env.LLM_MODEL;
 if(!endpoint||!key||!llm||!model)throw new HttpError('Falta conectar OCR y LLM para activar la extracción documental.',503);
 const base=new URL(endpoint);if(base.protocol!=='https:')throw new Error('Invalid OCR endpoint');const start=await fetch(new URL('/documentintelligence/documentModels/prebuilt-read:analyze?api-version=2024-11-30',base),{method:'POST',headers:{'Ocp-Apim-Subscription-Key':key,'Content-Type':'application/json'},body:JSON.stringify({base64Source:bytes.toString('base64')}),signal:AbortSignal.timeout(15000)});
 if(!start.ok)throw new HttpError('El proveedor OCR no pudo leer el documento.',502);const operation=start.headers.get('operation-location');if(!operation||new URL(operation).origin!==base.origin)throw new Error('Invalid OCR operation');
 let content='';for(let i=0;i<18;i++){await new Promise(r=>setTimeout(r,1400));const response=await fetch(operation,{headers:{'Ocp-Apim-Subscription-Key':key},signal:AbortSignal.timeout(5000)});if(!response.ok)throw new HttpError('Error consultando el OCR.',502);const result=await response.json();if(result.status==='failed')throw new HttpError('No se pudo leer el archivo. Prueba con una imagen más clara.',422);if(result.status==='succeeded'){content=result.analyzeResult?.content??'';break}}
 if(!content)throw new HttpError('El OCR no terminó o no encontró texto. Intenta nuevamente.',504);if(content.length>70000)throw new HttpError('Documento demasiado extenso para esta versión. Divide el expediente.',413);
 const llmURL=new URL(process.env.LLM_BASE_URL??'https://api.openai.com/v1/');if(llmURL.protocol!=='https:')throw new Error('Invalid LLM endpoint');
 const result=await fetch(new URL('chat/completions',llmURL.href.endsWith('/')?llmURL:new URL(llmURL.href+'/')),{method:'POST',headers:{Authorization:`Bearer ${llm}`,'Content-Type':'application/json'},body:JSON.stringify({model,temperature:0,response_format:{type:'json_object'},messages:[{role:'system',content:extractionPrompt},{role:'user',content:JSON.stringify({texto_documento:content})}]}),signal:AbortSignal.timeout(25000)});
 if(!result.ok)throw new HttpError('El servicio de extracción no está disponible.',502);const payload=await result.json();try{return parseExtraction(JSON.parse(payload.choices?.[0]?.message?.content??''))}catch{throw new HttpError('La IA devolvió campos inconsistentes. Revisa manualmente o vuelve a intentar.',422)}
}
