import {z} from 'zod';
import {context,requireStaff,failure,check,json,audit,HttpError} from '@/lib/server';
import {parseExtraction} from '@/lib/domain';
export const maxDuration=60;
export async function GET(request:Request){try{const {db}=await context(request);const id=z.uuid().parse(new URL(request.url).searchParams.get('id'));const r=await db.from('documentos').select('id,ruta').eq('id',id).maybeSingle();check(r.error);if(!r.data)throw new HttpError('Documento no disponible.',404);await audit(db,'DESCARGA_DOCUMENTO','documentos',id);const signed=await db.storage.from('documentos').createSignedUrl(r.data.ruta,60,{download:true});check(signed.error);return Response.json({url:signed.data?.signedUrl},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function POST(request:Request){try{const {db,profile}=await context(request);requireStaff(profile);if(request.headers.get('content-type')?.includes('application/json')){const b=await json(request);if(b.action!=='review')throw new HttpError('Acción desconocida.');const id=z.uuid().parse(b.id);const datos=parseExtraction(b.datos);const r=await db.from('documentos').update({datos,estado:'revisado'}).eq('id',id).select('id');check(r.error);if(!r.data?.length)throw new HttpError('Documento no disponible.',404);return Response.json({ok:true})}
 if(Number(request.headers.get('content-length')??0)>4.4*1024*1024)throw new HttpError('El máximo es 4 MB.',413);
 const f=await request.formData();const file=f.get('file');if(!(file instanceof File)||file.size===0||file.size>4*1024*1024)throw new HttpError('Archivo vacío o mayor de 4 MB.');
 const b=new Uint8Array(await file.arrayBuffer());const pdf=Buffer.from(b.subarray(0,5)).toString()==='%PDF-',png=b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71&&b[4]===13&&b[5]===10&&b[6]===26&&b[7]===10,jpg=b[0]===255&&b[1]===216&&b[2]===255;const mime=pdf?'application/pdf':png?'image/png':jpg?'image/jpeg':null;if(!mime||mime!==file.type)throw new HttpError('El contenido debe ser PDF, PNG o JPG válido.');
 const embarque_id=z.uuid().parse(f.get('embarque_id'));const tipo=z.enum(['Factura comercial','Packing list','BL marítimo','DUS','Otro']).parse(f.get('tipo'));const vence_el=z.preprocess(v=>v===''||v===null?null:v,z.string().date().nullable()).parse(f.get('vence_el'));const id=crypto.randomUUID();const ruta=`${profile.empresa_id}/${id}.${pdf?'pdf':png?'png':'jpg'}`;
 const r=await db.from('documentos').insert({id,empresa_id:profile.empresa_id,embarque_id,ruta,vence_el,nombre:file.name.replace(/[\x00-\x1f/\\]/g,'_').slice(0,150),tipo,visible_importador:f.get('visible_importador')==='on'});check(r.error);
 const upload=await db.storage.from('documentos').upload(ruta,b,{contentType:mime,upsert:false});if(upload.error){await db.from('documentos').delete().eq('id',id);throw new HttpError('No se pudo guardar el archivo. Vuelve a intentarlo.',503)}await audit(db,'ARCHIVO_GUARDADO','documentos',id);return Response.json({ok:true,id},{status:201})
 }catch(e){return failure(e)}}
